namespace Umbraco.Plugins.Connector.Helpers
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    public static class TimeZoneHelper
    {
        public static TimeZoneData[] AllTimeZones => AllTimeZonesCollection();
        /// <summary>
        /// taken from https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
        /// updated on August 2019
        /// </summary>
        /// <returns></returns>
        private static TimeZoneData[] AllTimeZonesCollection()
        {
            return new[]
            {
                new TimeZoneData("ACDT", "Australian Central Daylight Savings Time", "UTC+10:30"),
                new TimeZoneData("ACST", "Australian Central Standard Time", "UTC+09:30"),
                new TimeZoneData("ACT", "Acre Time", "UTC-05"),
                new TimeZoneData("ACT", "ASEAN Common Time", "UTC+06:30","UTC+09"),
                new TimeZoneData("ACWST", "Australian Central Western Standard Time", "UTC+08:45"),
                new TimeZoneData("ADT", "Atlantic Daylight Time", "UTC-03"),
                new TimeZoneData("AEDT", "Australian Eastern Daylight Savings Time", "UTC+11"),
                new TimeZoneData("AEST", "Australian Eastern Standard Time", "UTC+10"),
                new TimeZoneData("AFT", "Afghanistan Time", "UTC+04:30"),
                new TimeZoneData("AKDT", "Alaska Daylight Time", "UTC-08"),
                new TimeZoneData("AKST", "Alaska Standard Time", "UTC-09"),
                new TimeZoneData("ALMT", "Alma-Ata Time", "UTC+06"),
                new TimeZoneData("AMST", "Amazon Summer Time", "UTC-03"),
                new TimeZoneData("AMT", "Amazon Time", "UTC-04"),
                new TimeZoneData("AMT", "Armenia Time", "UTC+04"),
                new TimeZoneData("ANAT", "Anadyr Time", "UTC+12"),
                new TimeZoneData("AQTT", "Aqtobe Time", "UTC+05"),
                new TimeZoneData("ART", "Argentina Time", "UTC-03"),
                new TimeZoneData("AST", "Arabia Standard Time", "UTC+03"),
                new TimeZoneData("AST", "Atlantic Standard Time", "UTC-04"),
                new TimeZoneData("AWST", "Australian Western Standard Time", "UTC+08"),
                new TimeZoneData("AZOST", "Azores Summer Time", "UTC±00"),
                new TimeZoneData("AZOT", "Azores Standard Time", "UTC-01"),
                new TimeZoneData("AZT", "Azerbaijan Time", "UTC+04"),
                new TimeZoneData("BDT", "Brunei Time", "UTC+08"),
                new TimeZoneData("BIOT", "British Indian Ocean Time", "UTC+06"),
                new TimeZoneData("BIT", "Baker Island Time", "UTC-12"),
                new TimeZoneData("BOT", "Bolivia Time", "UTC-04"),
                new TimeZoneData("BRST", "Brasília Summer Time", "UTC-02"),
                new TimeZoneData("BRT", "Brasilia Time", "UTC-03"),
                new TimeZoneData("BST", "Bangladesh Standard Time", "UTC+06"),
                new TimeZoneData("BST", "Bougainville Standard Time", "UTC+11"),
                new TimeZoneData("BST", "British Summer Time", "UTC+01"),
                new TimeZoneData("BTT", "Bhutan Time", "UTC+06"),
                new TimeZoneData("CAT", "Central Africa Time", "UTC+02"),
                new TimeZoneData("CCT", "Cocos Islands Time", "UTC+06:30"),
                new TimeZoneData("CDT", "Central Daylight Time", "UTC-05"),
                new TimeZoneData("CDT", "Cuba Daylight Time", "UTC-04"),
                new TimeZoneData("CEST", "Central European Summer Time", "UTC+02"),
                new TimeZoneData("CET", "Central European Time", "UTC+01"),
                new TimeZoneData("CHADT", "Chatham Daylight Time", "UTC+13:45"),
                new TimeZoneData("CHAST", "Chatham Standard Time", "UTC+12:45"),
                new TimeZoneData("CHOT", "Choibalsan Standard Time", "UTC+08"),
                new TimeZoneData("CHOST", "Choibalsan Summer Time", "UTC+09"),
                new TimeZoneData("CHST", "Chamorro Standard Time", "UTC+10"),
                new TimeZoneData("CHUT", "Chuuk Time", "UTC+10"),
                new TimeZoneData("CIST", "Clipperton Island Standard Time", "UTC-08"),
                new TimeZoneData("CIT", "Central Indonesia Time", "UTC+08"),
                new TimeZoneData("CKT", "Cook Island Time", "UTC-10"),
                new TimeZoneData("CLST", "Chile Summer Time", "UTC-03"),
                new TimeZoneData("CLT", "Chile Standard Time", "UTC-04"),
                new TimeZoneData("COST", "Colombia Summer Time", "UTC-04"),
                new TimeZoneData("COT", "Colombia Time", "UTC-05"),
                new TimeZoneData("CST", "Central Standard Time", "UTC-06"),
                new TimeZoneData("CST", "China Standard Time", "UTC+08"),
                new TimeZoneData("CST", "Cuba Standard Time", "UTC-05"),
                new TimeZoneData("CT", "China Time", "UTC+08"),
                new TimeZoneData("CVT", "Cape Verde Time", "UTC-01"),
                new TimeZoneData("CWST", "Central Western Standard Time", "UTC+08:45"),
                new TimeZoneData("CXT", "Christmas Island Time", "UTC+07"),
                new TimeZoneData("DAVT", "Davis Time", "UTC+07"),
                new TimeZoneData("DDUT", "Dumont d'Urville Time", "UTC+10"),
                new TimeZoneData("DFT", "AIX-specific equivalent of Central European Time", "UTC+01"),
                new TimeZoneData("DST","Dateline Standard Time", "UTC-12"),
                new TimeZoneData("EASST", "Easter Island Summer Time", "UTC-05"),
                new TimeZoneData("EAST", "Easter Island Standard Time", "UTC-06"),
                new TimeZoneData("EAT", "East Africa Time", "UTC+03"),
                new TimeZoneData("ECT", "Eastern Caribbean Time", "UTC-04"),
                new TimeZoneData("ECT", "Ecuador Time", "UTC-05"),
                new TimeZoneData("EDT", "Eastern Daylight Time", "UTC-04"),
                new TimeZoneData("EEST", "Eastern European Summer Time", "UTC+03"),
                new TimeZoneData("EET", "Eastern European Time", "UTC+02"),
                new TimeZoneData("EGST", "Eastern Greenland Summer Time", "UTC±00"),
                new TimeZoneData("EGT", "Eastern Greenland Time", "UTC-01"),
                new TimeZoneData("EIT", "Eastern Indonesian Time", "UTC+09"),
                new TimeZoneData("EST", "Eastern Standard Time", "UTC-05"),
                new TimeZoneData("FET", "Further-eastern European Time", "UTC+03"),
                new TimeZoneData("FJT", "Fiji Time", "UTC+12"),
                new TimeZoneData("FKST", "Falkland Islands Summer Time", "UTC-03"),
                new TimeZoneData("FKT", "Falkland Islands Time", "UTC-04"),
                new TimeZoneData("FNT", "Fernando de Noronha Time", "UTC-02"),
                new TimeZoneData("GALT", "Galápagos Time", "UTC-06"),
                new TimeZoneData("GAMT", "Gambier Islands Time", "UTC-09"),
                new TimeZoneData("GET", "Georgia Standard Time", "UTC+04"),
                new TimeZoneData("GFT", "French Guiana Time", "UTC-03"),
                new TimeZoneData("GILT", "Gilbert Island Time", "UTC+12"),
                new TimeZoneData("GIT", "Gambier Island Time", "UTC-09"),
                new TimeZoneData("GMT", "Greenwich Mean Time", "UTC±00"),
                new TimeZoneData("GST", "South Georgia and the South Sandwich Islands Time", "UTC-02"),
                new TimeZoneData("GST", "Gulf Standard Time", "UTC+04"),
                new TimeZoneData("GYT", "Guyana Time", "UTC-04"),
                new TimeZoneData("HDT", "Hawaii–Aleutian Daylight Time", "UTC-09"),
                new TimeZoneData("HAEC", "Heure Avancée d'Europe Centrale French-language name for CEST", "UTC+02"),
                new TimeZoneData("HST", "Hawaii–Aleutian Standard Time", "UTC-10"),
                new TimeZoneData("HKT", "Hong Kong Time", "UTC+08"),
                new TimeZoneData("HMT", "Heard and McDonald Islands Time", "UTC+05"),
                new TimeZoneData("HOVST", "Hovd Summer Time", "UTC+08"),
                new TimeZoneData("HOVT", "Hovd Time", "UTC+07"),
                new TimeZoneData("ICT", "Indochina Time", "UTC+07"),
                new TimeZoneData("IDLW", "International Day Line West time zone", "UTC-12"),
                new TimeZoneData("IDT", "Israel Daylight Time", "UTC+03"),
                new TimeZoneData("IOT", "Indian Ocean Time", "UTC+03"),
                new TimeZoneData("IRDT", "Iran Daylight Time", "UTC+04:30"),
                new TimeZoneData("IRKT", "Irkutsk Time", "UTC+08"),
                new TimeZoneData("IRST", "Iran Standard Time", "UTC+03:30"),
                new TimeZoneData("IST", "Indian Standard Time", "UTC+05:30"),
                new TimeZoneData("IST", "Irish Standard Time", "UTC+01"),
                new TimeZoneData("IST", "Israel Standard Time", "UTC+02"),
                new TimeZoneData("JST", "Japan Standard Time", "UTC+09"),
                new TimeZoneData("KALT", "Kaliningrad Time", "UTC+02"),
                new TimeZoneData("KGT", "Kyrgyzstan Time", "UTC+06"),
                new TimeZoneData("KOST", "Kosrae Time", "UTC+11"),
                new TimeZoneData("KRAT", "Krasnoyarsk Time", "UTC+07"),
                new TimeZoneData("KST", "Korea Standard Time", "UTC+09"),
                new TimeZoneData("LHST", "Lord Howe Standard Time", "UTC+10:30"),
                new TimeZoneData("LHST", "Lord Howe Summer Time", "UTC+11"),
                new TimeZoneData("LINT", "Line Islands Time", "UTC+14"),
                new TimeZoneData("MAGT", "Magadan Time", "UTC+12"),
                new TimeZoneData("MART", "Marquesas Islands Time", "UTC-09:30"),
                new TimeZoneData("MAWT", "Mawson Station Time", "UTC+05"),
                new TimeZoneData("MDT", "Mountain Daylight Time", "UTC-06"),
                new TimeZoneData("MET", "Middle European Time Same zone as CET", "UTC+01"),
                new TimeZoneData("MEST", "Middle European Summer Time Same zone as CEST", "UTC+02"),
                new TimeZoneData("MHT", "Marshall Islands Time", "UTC+12"),
                new TimeZoneData("MIST", "Macquarie Island Station Time", "UTC+11"),
                new TimeZoneData("MIT", "Marquesas Islands Time", "UTC-09:30"),
                new TimeZoneData("MMT", "Myanmar Standard Time", "UTC+06:30"),
                new TimeZoneData("MSK", "Moscow Time", "UTC+03"),
                //new TimeZoneData("MST", "Malaysia Standard Time", "UTC+08"),
                new TimeZoneData("MST", "Mountain Standard Time", "UTC-07"),
                new TimeZoneData("MUT", "Mauritius Time", "UTC+04"),
                new TimeZoneData("MVT", "Maldives Time", "UTC+05"),
                new TimeZoneData("MYT", "Malaysia Time", "UTC+08"),
                new TimeZoneData("NCT", "New Caledonia Time", "UTC+11"),
                new TimeZoneData("NDT", "Newfoundland Daylight Time", "UTC-02:30"),
                new TimeZoneData("NFT", "Norfolk Island Time", "UTC+11"),
                new TimeZoneData("NOVT", "Novosibirsk Time", "UTC+07"),
                new TimeZoneData("NPT", "Nepal Time", "UTC+05:45"),
                new TimeZoneData("NST", "Newfoundland Standard Time", "UTC-03:30"),
                new TimeZoneData("NT", "Newfoundland Time", "UTC-03:30"),
                new TimeZoneData("NUT", "Niue Time", "UTC-11"),
                new TimeZoneData("NZDT", "New Zealand Daylight Time", "UTC+13"),
                new TimeZoneData("NZST", "New Zealand Standard Time", "UTC+12"),
                new TimeZoneData("OMST", "Omsk Time", "UTC+06"),
                new TimeZoneData("ORAT", "Oral Time", "UTC+05"),
                new TimeZoneData("PDT", "Pacific Daylight Time", "UTC-07"),
                new TimeZoneData("PET", "Peru Time", "UTC-05"),
                new TimeZoneData("PETT", "Kamchatka Time", "UTC+12"),
                new TimeZoneData("PGT", "Papua New Guinea Time", "UTC+10"),
                new TimeZoneData("PHOT", "Phoenix Island Time", "UTC+13"),
                new TimeZoneData("PHT", "Philippine Time", "UTC+08"),
                new TimeZoneData("PKT", "Pakistan Standard Time", "UTC+05"),
                new TimeZoneData("PMDT", "Saint Pierre and Miquelon Daylight Time", "UTC-02"),
                new TimeZoneData("PMST", "Saint Pierre and Miquelon Standard Time", "UTC-03"),
                new TimeZoneData("PONT", "Pohnpei Standard Time", "UTC+11"),
                new TimeZoneData("PST", "Pacific Standard Time", "UTC-08"),
                new TimeZoneData("PST", "Philippine Standard Time", "UTC+08"),
                new TimeZoneData("PYST", "Paraguay Summer Time", "UTC-03"),
                new TimeZoneData("PYT", "Paraguay Time", "UTC-04"),
                new TimeZoneData("RET", "Réunion Time", "UTC+04"),
                new TimeZoneData("ROTT", "Rothera Research Station Time", "UTC-03"),
                new TimeZoneData("SAKT", "Sakhalin Island Time", "UTC+11"),
                new TimeZoneData("SAMT", "Samara Time", "UTC+04"),
                new TimeZoneData("SAST", "South African Standard Time", "UTC+02"),
                new TimeZoneData("SBT", "Solomon Islands Time", "UTC+11"),
                new TimeZoneData("SCT", "Seychelles Time", "UTC+04"),
                new TimeZoneData("SDT", "Samoa Daylight Time", "UTC-10"),
                new TimeZoneData("SGT", "Singapore Time", "UTC+08"),
                new TimeZoneData("SLST", "Sri Lanka Standard Time", "UTC+05:30"),
                new TimeZoneData("SRET", "Srednekolymsk Time", "UTC+11"),
                new TimeZoneData("SRT", "Suriname Time", "UTC-03"),
                new TimeZoneData("SST", "Samoa Standard Time", "UTC-11"),
                new TimeZoneData("SST", "Singapore Standard Time", "UTC+08"),
                new TimeZoneData("SYOT", "Showa Station Time", "UTC+03"),
                new TimeZoneData("TAHT", "Tahiti Time", "UTC-10"),
                new TimeZoneData("THA", "Thailand Standard Time", "UTC+07"),
                new TimeZoneData("TFT", "French Southern and Antarctic Time", "UTC+05"),
                new TimeZoneData("TJT", "Tajikistan Time", "UTC+05"),
                new TimeZoneData("TKT", "Tokelau Time", "UTC+13"),
                new TimeZoneData("TLT", "Timor Leste Time", "UTC+09"),
                new TimeZoneData("TMT", "Turkmenistan Time", "UTC+05"),
                new TimeZoneData("TRT", "Turkey Time", "UTC+03"),
                new TimeZoneData("TOT", "Tonga Time", "UTC+13"),
                new TimeZoneData("TVT", "Tuvalu Time", "UTC+12"),
                new TimeZoneData("ULAST", "Ulaanbaatar Summer Time", "UTC+09"),
                new TimeZoneData("ULAT", "Ulaanbaatar Standard Time", "UTC+08"),
                new TimeZoneData("UTC", "Coordinated Universal Time", "UTC±00"),
                new TimeZoneData("UYST", "Uruguay Summer Time", "UTC-02"),
                new TimeZoneData("UYT", "Uruguay Standard Time", "UTC-03"),
                new TimeZoneData("UZT", "Uzbekistan Time", "UTC+05"),
                new TimeZoneData("VET", "Venezuelan Standard Time", "UTC-04"),
                new TimeZoneData("VLAT", "Vladivostok Time", "UTC+10"),
                new TimeZoneData("VOLT", "Volgograd Time", "UTC+04"),
                new TimeZoneData("VOST", "Vostok Station Time", "UTC+06"),
                new TimeZoneData("VUT", "Vanuatu Time", "UTC+11"),
                new TimeZoneData("WAKT", "Wake Island Time", "UTC+12"),
                new TimeZoneData("WAST", "West Africa Summer Time", "UTC+02"),
                new TimeZoneData("WAT", "West Africa Time", "UTC+01"),
                new TimeZoneData("WEST", "Western European Summer Time", "UTC+01"),
                new TimeZoneData("WET", "Western European Time", "UTC±00"),
                new TimeZoneData("WIT", "Western Indonesian Time", "UTC+07"),
                new TimeZoneData("WST", "Western Standard Time", "UTC+08"),
                new TimeZoneData("YAKT", "Yakutsk Time", "UTC+09"),
                new TimeZoneData("YEKT", "Yekaterinburg Time", "UTC+05")
            };
        }
    }

    public class TimeZoneData
    {
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public string UtcOffsetDisplay { get; set; }
        public string EndOffset { get; set; }
        public TimeZoneData(string abbreviation, string name, string offset, string endOffset="")
        {
            Abbreviation = abbreviation;
            Name = name;
            UtcOffsetDisplay = offset;
            if (!string.IsNullOrEmpty(endOffset)) EndOffset = endOffset;
        }
    }
}
